#
# data storage:
#
# a. global map for relative pose estimation using lidar frontend:
map_path: /home/euvill/Desktop/kitti_test/filtered_map.pcd

#
# point cloud map & measurement processors
# 
# a. global map filter:
global_map_filter: voxel_filter                                 # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter

# b.1. local map segmenter: 
box_filter_size: [-150.0, 150.0, -150.0, 150.0, -150.0, 150.0]  # 参数顺序是min_x, max_x, min_y, max_y, min_z, max_z
# b.2. local map filtering:
local_map_filter: voxel_filter                                  # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter

# c. current frame filter
frame_filter: voxel_filter                                      # 选择当前帧点云滤波方法，目前支持：voxel_filter、no_filter

#
# relative pose estimation using lidar frontend
#
registration_method: NDT                                        # 选择点云匹配方法，目前支持：NDT 


# 各配置选项对应参数
## 滤波相关参数
voxel_filter:
    global_map:
        leaf_size: [0.9, 0.9, 0.9]
    local_map:
        leaf_size: [0.5, 0.5, 0.5]
    frame:
        leaf_size: [1.5, 1.5, 1.5]

## 匹配相关参数
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
